### PR TITLE
import a few CSV files into sqlite

### PR DESCRIPTION
**Pull request by philschatz**
This adds a script that imports CSV files into a SQLite Database stored in `./db`.

See `README.md` for instructions :smile:

### CODE REVIEW

**Comment by philschatz** [comment]
This populates the sqlite DB on OSX. I'm guessing something similar could be done to get it working in Windows. Any thoughts @aaroncampf ?

I think the only thing that would be needed is to write a `script/setup.bat` similar to the `script/setup` in here. I tried to add comments in the file but can help answer questions

**Comment by kielejocain** [comment]
I made a small edit to pull in what I believe is the correct version of the 2014 data (the one containing the `SchoolID` column.  Thoughts?

Since I did that, I didn't feel right doing the merge.  Otherwise, the script looks great.  Thanks, Phil!

**Comment by aaroncampf** [comment]
@philschatz I think you just need to use something other than Bash, but yes, I think it would still work

**Comment by philschatz** [comment]
Thanks! Once this is merged (and a fuller list of CSV files is made) we can delete the unused files (unless @kielejocain already knows which ones are bad since he made the original files :smile: )

**Comment by AnisriM** [comment]
I've created the _setup.bat_ file for windows similar to the _script/setup_ for OSX. Also slightly modified the script that imports CSV files into a SQLite Database stored in ./db, so that we can run the script independently without replacing the entire database just to replace the tables **if required** in future. Please review and let me know if I need to make any changes.
[Setup batch for Windows and Script.zip](https://github.com/philschatz/ed-pathways/files/184795/Setup.and.Script.zip)

**Pull request merged**
